name: flake-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / flake8 linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10'
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Install Flake8
        run: |
          pip install flake8 flake8-annotations flake8-bandit flake8-docstrings
      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics
